### ISSUE TITLE
运行到上传固件发布就 卡死

### ISSUE THREAD

**Issue by Jianfei-DinG** [Jason6111/OpenWrt_Personal#1]
为何我的运行到上传固件发布就 卡死呢 请教是什么原因
![QQ图片20230110164813](https://user-images.githubusercontent.com/96579381/211504149-00309530-b070-4b23-9fc9-807dc25e0428.png)

**Comment by Jason6111** [comment]
key给它了嘛 需要建立个key

**Comment by Jason6111** [comment]
右上角你的头像Settings-Developer settings-Personal access tokens-Generate new token-名为：ACTIONS_TRIGGER-设置有效期可以选择无有效期-下面勾选 
repo  
  repo:status  
  repo_deployment 
  public_repo 
  repo:invite  
  security_events
delete_repo
点击Generate token - 复制TOKEN备用
你的这个项目 Settings-Secrets and variable-Action— New repository secret-命名“ ACTIONS_TRIGGER_OPENWRT” 粘贴刚才token 保存
如果想使用TG机器通知 操作如下：你的这个项目 Settings-Secrets and variable-Action— New repository secret-命名“TGID“-数值是单纯数字那个再建一个“TG_TOKEN”-数值是“124135:xxxxxxx”（你机器TG的这个TOKEN）

**Comment by Jason6111** [comment]
还有在你actions-openwrt-x86 往下找其实已经有做好的固件了

**Comment by Jianfei-DinG** [comment]
谢谢你的解答：
但是你上面描述的这部份我不知道 是什么意思。
-----------------------------------------------------
repo
repo:status
repo_deployment
public_repo
repo:invite
security_events
delete_repo
点击Generate token - 复制TOKEN备用
你的这个项目 Settings-Secrets and variable-Action— New repository secret-命名“ ACTIONS_TRIGGER_OPENWRT” 粘贴刚才token 保存

**Comment by Jason6111** [comment]
就是没给上传操作权限 所以发不出来 但固件是编译完整的

**Comment by Jianfei-DinG** [comment]
好像是这样对吧！
----------------------------
![image](https://user-images.githubusercontent.com/96579381/211570960-60803bc0-c525-4075-ad05-6c052cf4e686.png)

**Comment by Jason6111** [comment]
里面的token是从 你头像设置那里获得的嘛 我提到的repo权限也给了的话就没问题 还有我看你也用了p3大佬的 请把你x86.config 重名为.config才能正确识别 用谁的都一样顺手就好

**Comment by Jianfei-DinG** [comment]
是这些权限吗？ 好像没设置
------------------------
![image](https://user-images.githubusercontent.com/96579381/211573889-3b5f5c18-64a6-4cbf-a556-6a222e22597c.png)

**Comment by Jianfei-DinG** [comment]
p3大佬的也卡在 编译固件那个位置 报错

**Comment by Jason6111** [comment]
右上角你的头像Settings-Developer settings-Personal access tokens-Generate new token-名为：ACTIONS_TRIGGER-设置有效期可以选择无有效期-下面勾选
![603DAD3A-34C4-4679-888F-145CA05C10BD](https://user-images.githubusercontent.com/43496459/211575394-44519484-c96b-42b4-83c6-f2f835bc0454.png)
![4753906E-BE8B-476E-9497-11B7E3972B2A](https://user-images.githubusercontent.com/43496459/211575412-af41d05f-a3dc-43f9-832c-cc943ea71511.png)

**Comment by Jason6111** [comment]
p3大佬默认是.config 我修改了是x86.config 是支持编译多设备的

**Comment by Jason6111** [comment]
上传脚本里有一个github_token 为了不外泄所以要自己设置我之前说的那两步

**Comment by Jianfei-DinG** [comment]
完全明白了。谢谢大佬的耐心解答。
